### ISSUE TITLE
Switch to pyproject.toml

### ISSUE THREAD

**Issue by prabhu** [AppThreat/dep-scan#102]
It's time to switch. Looking forward to some contributions.

https://drivendata.co/blog/python-packaging-2023
https://github.com/drivendataorg/nbautoexport/pull/113
https://github.com/drivendataorg/cloudpathlib/pull/324/files

**Comment by cerrussell** [comment]
Hi @prabhu, I'm well on the way to building out the toml for this. Seems to be running smoothly but I wondered what your expectation is in regards to the continued existence of setup.py and pytest.ini. I know preserving the former is sometimes necessary as the pyproject.toml spec is still evolving - but that doesn't seem to be the case here. Regarding pytest.ini, I have added a tool section to the toml, but running the tests will still default to the ini file as long as it exists.

**Comment by prabhu** [comment]
Hi @cerrussell. Thank you so much for your help!

Can we keep those files but switch the build and release pipelines to use the toml? Very excited already here!
