### ISSUE TITLE
clarify environment variable for vuln caching

### ISSUE THREAD

**Issue by stevesea** [AppThreat/dep-scan#19]
docs in dep-scan say to use VULNDB_HOME environment variable to cache download.

But, the vdb library uses VDB_HOME https://github.com/AppThreat/vulnerability-db/blob/master/vdb/lib/config.py#L19

**Comment by prabhu** [comment]
Hi @stevesea 

Good find! Code is obviously correct. I had to rename things to satisfy a trademark infringement claim a while ago. Will update the docs. Btw, please feel free to check out the parent project called scan which include dep-scan with other static analysis tools https://slscan.io

**Comment by prabhu** [comment]
`VDB_HOME` is the correct variable. Updated the readme.
