### ISSUE TITLE
False positives and false negatives

### ISSUE THREAD

**Issue by gitnachogo** [AppThreat/dep-scan#21]
Hi! 
My name is Nacho, and I am working on a research of many security testing tools such as ShiftLeft.
I would like to know if there has been any benchmark test of dep-scan to get the FP and FN of this tool (i am intested in maven dependencies specially).
Thanks for answering!!

**Comment by prabhu** [comment]
@gitnachogo Nice to meet you. Happy to help with your research by email: My email is prabhu @ shiftleft .io
