### ISSUE TITLE
Incorrect dependency "minio" linked by  python project depscan

### ISSUE THREAD

**Issue by BakanovKirill** [AppThreat/dep-scan#30]
Incorrect github project linked via python dependencies resolver during scan..
So when doing:
`pip install minio` 
you actually install `minio-py` not `minio` package.  

Actual result:

- Github link in the report is: https://github.com/minio/minio/releases 

Expected:

- https://github.com/minio/minio-py/releases instead. 
- and no error because latest version is installed.

<img width="1167" alt="Screenshot 2021-01-25 at 9 29 53 PM" src="https://user-images.githubusercontent.com/1275854/105767887-4d1c4a00-5f64-11eb-9f8f-9b6bc80b9926.png">

**Comment by prabhu** [comment]
Thank you. This is resolved with https://github.com/AppThreat/vulnerability-db/commit/ace0ca033d8776a8268664cb4a5c69d447109446
