### ISSUE TITLE
Clarify pkg_min_users

### ISSUE THREAD

**Issue by matkoniecz** [AppThreat/dep-scan#38]
https://github.com/AppThreat/dep-scan#package-risk-audit 

"Package has less than 2 npm users" - it likely should be either "JS package has less than 2 npm users" or "Package has less than 2 npm/pip users"

Or Python packages have unfairly increased risk score

**Comment by prabhu** [comment]
Thanks, @matkoniecz, for the query. The min users check is currently available only for npm since this information is not available from pypi.

https://github.com/AppThreat/dep-scan/blob/9e07951664788bd750e8cb49444d069dba3c64ca/depscan/lib/pkg_query.py#L400
