### ISSUE TITLE
Issue when used within docker for GHA

### ISSUE THREAD

**Issue by jchli** [AppThreat/dep-scan#62]
We're seeing this error when using dep-scan through a container in github actions. 

invocation:
`/usr/bin/docker run --name quayioappthreatdepscanlatest_e516a4 --label 290506 --workdir /github/workspace --rm -e "IsRunningOnCI" -e "Environment" -e "DOTNET_ROOT" -e "VDB_HOME" -e "GITHUB_TOKEN" -e "INPUT_SRC" -e "INPUT_REPORT_FILE" -e "INPUT_BOM" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/carrot-app/carrot-app":"/github/workspace" quay.io/appthreat/dep-scan:latest  "scan" "--src" "/github/workspace" "--report_file" "/github/workspace/reports/depscan.json"
`

```
  ___            _____ _                    _
 / _ \          |_   _| |                  | |
/ /_\ \_ __  _ __ | | | |__  _ __ ___  __ _| |_
|  _  | '_ \| '_ \| | | '_ \| '__/ _ \/ _` | __|
| | | | |_) | |_) | | | | | | | |  __/ (_| | |_
\_| |_/ .__/| .__/\_/ |_| |_|_|  \___|\__,_|\__|
      | |   | |
      |_|   |_|

Traceback (most recent call last):
  File "/usr/local/bin/scan", line 33, in <module>
    sys.exit(load_entry_point('appthreat-depscan==2.2.0', 'console_scripts', 'scan')())
  File "/usr/local/lib/python3.9/site-packages/appthreat_depscan-2.2.0-py3.9.egg/depscan/cli.py", line 242, in main
    project_types_list = utils.detect_project_type(src_dir)
  File "/usr/local/lib/python3.9/site-packages/appthreat_depscan-2.2.0-py3.9.egg/depscan/lib/utils.py", line [15](https://github.com/carrotfertility/carrot-app/actions/runs/3447575122/jobs/5753722505#step:6:16)6, in detect_project_type
    if find_files(src_dir, ".github", "workflows", "*.yml", quick=True):
TypeError: find_files() got multiple values for argument 'quick'

**Comment by prabhu** [comment]
@jchli This bug was fixed in 2.2.1. I am trying to find the login for quay.io to force a rebuild which doesn't seem to be working for some reason.

**Comment by prabhu** [comment]
@jchli Could you please try again?

**Comment by jchli** [comment]
@prabhu appears to be working now. thanks!
