### ISSUE TITLE
Investigate re-using this project as a container scanning tool

### ISSUE THREAD

**Issue by prabhu** [AppThreat/dep-scan#8]
It should be possible to use [docker-py](https://github.com/docker/docker-py) and some platform specific ways of listing packages (like `rpm -qa`) to create a container or OS scanner tool with this repo. Have to think about a way of differentiating this from the likes of trivy and anchore though since the world doesn't need yet another container scanner.

May be grafeas support might help sell things a bit but not sure what else we could do.

**Comment by jeff-cook** [comment]
One difference is the creation of a sBOM. This would then allow someone to check for approved/unapproved licenses.

**Comment by prabhu** [comment]
@jeff-cook 
v2.0.0 is released with support for container image scanning for application related vulnerabilities. Also includes license scanning support.
