### ISSUE TITLE
dep-scan silently fails when run in docker container as referenced in README

### ISSUE THREAD

**Issue by ahaynes-mission** [AppThreat/dep-scan#89]
### Environment
GitLab CI/CD with Docker using the following command
```shell
docker run --user $(id -u):$(id -g) \
  --rm \
  -e GITHUB_TOKEN=$GITHUB_TOKEN \
  -e VDB_HOME=/app/appthreat \
  -e DEPSCAN_REPORTS_DIR=/app/reports \
  -e VDB_CACHE=/app/appthreat/cache \
  -v $CI_PROJECT_DIR:/app gchr.io/appthreat/dep-scan \
  scan --src /app/requirements --report_file /app/reports/depscan.json
```

### Expected behavior
dep-scan should automatically generate an SBoM with `cdxgen` to use for scanning for vulns.

### Actual behavior:
dep-scan silently fails to generate an SBoM and performs no scan.

---
A quick work-around that got us back up and running was modifying our docker command to pass the `-e GLOBAL_NODE_MODULES_PATH=/usr/local/lib/node-modules` flag so that `npm` knows where to look for modules.

It appears that when dep-scan runs without passing in a BOM file, it tries to generate one with `cdxgen`. `cdxgen` relies upon the `GLOBAL_NODE_MODULES_PATH` environment variable or `npm` to function properly. If the environment variable isn't present, it falls back to `npm` to determine the modules path by using `npm root --quiet -g`, but `cdxgen` when being run in the python subprocess doesn't return an error, however it will return an error if called directly
```shell
❯ docker run --rm ghcr.io/appthreat/dep-scan /usr/local/lib/node_modules/@appthreat/cdxgen/bin/cdxgen
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
node:internal/validators:163
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:393:5)
    at validateString (node:internal/validators:163:11)
    at Object.join (node:path:1172:7)
    at Object.<anonymous> (/usr/local/lib/node_modules/@appthreat/cdxgen/binary.js:58:30)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v18.12.1
```

A few hours of tinkering around led me to find that the root cause of this is the `npm` install on the published container is non-functional. This appears to be because when the docker container is being built, the COPY that copies npm into the secondary container from build-env does not preserve the symlink, causing `npm` to look in the wrong directory for certain files and modules.

Docker does not preserve symlinks when `COPY`ing files directly, but does preserve symlinks when `COPY`ing a directory.

Changing [these lines of the dockerfile](https://github.com/AppThreat/dep-scan/blob/master/Dockerfile#L75-L79) to instead copy the entire `/usr/local/bin/` directory solved this in my local testing.

**Comment by prabhu** [comment]
@ahaynes-mission, Could you kindly share a PR? This is an excellent investigation.

**Comment by ahaynes-mission** [comment]
Hi @prabhu, it seems your latest release has addressed this issue. I'm seeing that the docker container is now properly building an SBOM before performing a scan and reporting any Issues/CVEs that it finds when ran as documented.

**Comment by prabhu** [comment]
Thank you for reporting the issue along with offering a solution!
