### ISSUE TITLE
Ask: can i run dep-scan to generate SBOM only

### ISSUE THREAD

**Issue by ngocnn97** [AppThreat/dep-scan#91]
Hi.
I am using dep-scan in my Jenkins Pipeline, Can I just generate SBOM of dependency without parsing, to reduce pipeline time

**Comment by prabhu** [comment]
@ngocnn97 dep-scan internally uses my other project called [cdxgen](https://github.com/CycloneDX/cdxgen) so best to invoke that directly.

https://github.com/CycloneDX/cdxgen

**Comment by ngocnn97** [comment]
Thanks you !
